#How to format input data type into numbered data type. 
x = int(input("int01 (Make it large): "))
y = int(input("int02 (Make it large): "))
a = float(input("float01: "))
b = float(input("float02: "))
print("\n")

#What are the types of operations you knew and how to do them?
print("FOR INTERGERS OPERATIONS") 
print("Addition of two numbers is: ", x + y)
print("Substraction of two numbers is: ", x - y)
print("Multiplication of two numbers is: ", x * y)
print("Division of two numbers is: ", x / y)
print("Remainder of two numbers is: ", x % y)
print("Square of two numbers is: ", x * x, "and", y * y)
print("Power over one another is: ", pow(x, y))
print("\n")
print("FOR FLOATING POINTS OPERATIONS")
print("Addition of two numbers is: ", a + b)
print("Substraction of two numbers is: ", a - b)
print("Multiplication of two numbers is: ", a * b)
print("Division of two numbers is: ", a / b)
print("Remainder of two numbers is: ", a % b)
print("Square of two numbers is: ", a * a, "and", b * b)
print("Power over one another is: ", pow(a, b))
print("\n")

#How to add commas for readability? 
print(f"If we have to add coma to integers, the result is {x*y:,}")
print(f"If we have to add coma to floating points, the result is {a*b:,}")
print("\n")

#What are the two ways to estimate a number? 
print(f"If we have to estimate the integers, the result is {x*y:.2f}")
print(f"If we have to estimate the floating points, the result is {a*b:.2f}")
print("\n")
roundINT = round(x*y, 3)
roundFP = round(a*b, 3)
print(f"If we have to round the integers, the result is {roundINT}")
print(f"If we have to round the floating points, the result is {roundFP}")
print("\n")